# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: "npm"
      - name: installnpm
        run: npm install
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: "npm"
      - name: installnpm
        run: npm install
      - name: test db Users
        run: npm run test -- tests/dbusers.test.js --json --outputFile=test-results.json
      - name: test add db Clients
        run: npm run test -- tests/dbclients-add.test.js --json --outputFile=test-results.json
      - name: test add db Demandes
        run: npm run test -- tests/dbdemandes-add.test.js --json --outputFile=test-results.json
      - name: test delete db Clients
        run: npm run test -- tests/dbclients-delete.test.js --json --outputFile=test-results.json
      - name: test delete db Demandes
        run: npm run test -- tests/dbdemandes-delete.test.js --json --outputFile=test-results.json
